camera:
  source: rtsp
  device_id: null
  rtsp_url: rtsp://root:test@192.168.50.153/axis-media/media.amp?resolution=1920x1080
  legacy_url: null
display:
  timer: 5
  background_color: '#FFE8D4'
  font_color: '#032F5C'
  use_background_image: false
  background_image: null
  font_family: Inter
  font_size: medium
recognition:
  threshold: 0.5
  draw_boxes: true
system:
  database_path: system/Attendance.db
  encodings_path: images/
  rtsp_pickle: system/rtspin.pkl
