name: build-push
on: workflow_dispatch
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set lowercase image name
        id: lowercase
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Extract versions from package.json files
        id: version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image exists
        id: version-check
        run: |
          if docker manifest inspect ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }} >/dev/null 2>&1; then
            echo "Image ${{ steps.version.outputs.VERSION }} already exists"
            echo "EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Image ${{ steps.version.outputs.VERSION }} does not exist"
            echo "EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Backend image
        if: steps.version-check.outputs.EXISTS == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
